
Command_fwd=['mne_do_forward_solution --meas /autofs/cluster/transcend/MEG/fix/' subj '/X/' subj '_fix_1_raw.fif --megonly --overwrite ' ... 
    ' --spacing  oct-5  --mri ' '/autofs/cluster/transcend/MEG/erm/' subj '/X/' subj '_1-trans.fif    --subject  ' subj  ...
    ' --fwd  /autofs/cluster/transcend/MEG/fix/' subj '/X/' subj '-oct_fix_1-fwd.fif '];


Command_inv =[' mne_do_inverse_operator --meg --fixed   --noiserank 61 ' ...
    ' --fwd /autofs/cluster/transcend/MEG/fix/' subj '/X/' subj '-oct_fix_1-fwd.fif --proj /autofs/cluster/transcend/MEG/fix/' subj '/X/' subj '_fix_1_ecg_proj.fif '...
    '  --proj /autofs/cluster/transcend/MEG/fix/' subj '/X/' subj '_fix_1_eog_proj.fif  '....
    ' --senscov /autofs/cluster/transcend/MEG/fix/' subj '/X/' subj '_erm_1_0.1-144fil-cov.fif   ' ...
   '  '...
   ' --inv /autofs/cluster/transcend/MEG/fix/' subj '/X/' subj '_fix_0.1_144_fil_fixed_new_erm_megreg_0_new_MNE_proj-inv.fif ' ...
  '  '];


[s,r]=unix(Command_fwd)

[s,r]=unix(Command_inv)
